### ISSUE TITLE
`dmarc2html` fails

### ISSUE THREAD

**Issue by catap** [palant/opensmtpd-filters#1]
as
```
Dec 27 20:37:04 mx1 smtpd[35753]: 1346581649bf5965 smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
Dec 27 20:37:05 mx1 smtpd[86029]: dmarc2html: Traceback (most recent call last):
Dec 27 20:37:05 mx1 smtpd[86029]: dmarc2html:   File "/usr/local/libexec/palant-opensmtpd-filters/venvs/opensmtpd-filters/lib/python3.10/site-packages/opensmtpd_filters/dmarc2html_filter.py", line 43, in convert
Dec 27 20:37:05 mx1 smtpd[86029]: dmarc2html:     raise Exception('Expected one attachment, got {}'.format(len(attachments)))
Dec 27 20:37:05 mx1 smtpd[86029]: dmarc2html: Exception: Expected one attachment, got 0
Dec 27 20:37:05 mx1 smtpd[35753]: 1346581649bf5965 smtp message msgid=a5f441d1 size=4842 nrcpt=1 proto=ESMTP
Dec 27 20:37:05 mx1 smtpd[35753]: 1346581649bf5965 smtp envelope evpid=a5f441d1c8eaf563 from=<kirill.korinsky@icloud.com> to=<dmarc-report@catap.net>
```

on attached zip from google

[google.com!korins.ky!1703548800!1703635199.zip](https://github.com/palant/opensmtpd-filters/files/13780822/google.com.korins.ky.1703548800.1703635199.zip)

**Comment by catap** [comment]
I can easy reproduce that issue by sending this zip from icloud to dmarc's report domain.

**Comment by palant** [comment]
The problem is not the zip file. It’s not being recognized as an attachment. So: what does the email look like? Maybe you could save it as a `.eml` file and attach it here. Alternatively, email source code starting with the `Content-Type` header and ending at the beginning of the ZIP attachment should also do.

**Comment by catap** [comment]
Sure, here the email: 
[Report domain_ korins.ky Submitter_ google.com Report-ID_ 440465233067844141.zip](https://github.com/palant/opensmtpd-filters/files/13781972/Report.domain_.korins.ky.Submitter_.google.com.Report-ID_.440465233067844141.zip)

(github asked me to make a zip from it)

**Comment by palant** [comment]
Yes, I can confirm that this message cannot be processed correctly. But that’s a message sent by your iCloud account, with complicated structure and multiple nested parts. A regular Google message looks very differently and is processed correctly.

I’m looking into whether the parsing logic can be adapted, but I don’t think that this use case justifies making it considerably more complicated than it is now.

**Comment by catap** [comment]
Indeed it's more complicated.

I simple tried to test that filter O:-)

**Comment by palant** [comment]
Turned out to be fairly simple after all. I think that it should work even with those iCloud mails now.

**Comment by catap** [comment]
Something still doesn't right. I've attached resulted email and screenshot how I see it via mail.app:

<img width="1285" alt="Screenshot 2023-12-28 at 00 46 45" src="https://github.com/palant/opensmtpd-filters/assets/37775/fdfe867e-265b-47c6-930c-a497bff442ab">

[Report domain_ korins.ky Submitter_ google.com Report-ID_ 440465233067844141.zip](https://github.com/palant/opensmtpd-filters/files/13782109/Report.domain_.korins.ky.Submitter_.google.com.Report-ID_.440465233067844141.zip)

**Comment by catap** [comment]
and Thunderbird show it as it should

**Comment by palant** [comment]
I suspect that your email client has trouble displaying a `multipart/alternate` message structured like this. I pushed one more change, feel free to try it.

**Comment by catap** [comment]
Well... it doesn't help. I still see `Content-Type: multipart/alternative` header: 
[qqq.zip](https://github.com/palant/opensmtpd-filters/files/13782419/qqq.zip)

Thus, the right structure should be something like this: https://stackoverflow.com/a/66551704

**Comment by palant** [comment]
My bad. I trusted the documentation here and didn’t actually test. Yet the documentation appears to be incorrect and `multipart/alternative` isn’t actually being converted.

**Comment by catap** [comment]
an example of real life dmarc report with quite complicated strucutre: 
[Report Domain_ korins.ky Submitter_ protection.outlook.com Report-ID_ 3fcd42495e724333a793ad0ca6b4950f.zip](https://github.com/palant/opensmtpd-filters/files/13792746/Report.Domain_.korins.ky.Submitter_.protection.outlook.com.Report-ID_.3fcd42495e724333a793ad0ca6b4950f.zip)

**Comment by palant** [comment]
Not really, these were processed correctly before this change as well – they have `multipart/mixed` at the top level, so the attachment is found without any trouble. The problem only occurred when the attachment was hidden within a nested structure.
